package com.rital.myexpensetracker.data.local.entity
import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import com.rital.myexpensetracker.utils.Constatnts

/**
 * Represents an expense record in the database.
 *
 * @param id The unique identifier for the expense, auto-generated by the database.
 * @param type The type of expense (e.g., "Income", "Expense").
 * @param amount The monetary value of the expense.
 * @param date The date of the expense, stored as a Long (timestamp).
 * @param comment An optional comment or note about the expense.
 * @param category The category of the expense (e.g., "Food", "Transport").
 * @param paymentMode The method of payment (e.g., "Cash", "Credit Card").
 */
@Entity(tableName = Expense.TABLE_NAME)
data class Expense(
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = COLUMN_ID)
    val id: Long = Constatnts.ZERO,

    @ColumnInfo(name = COLUMN_TYPE)
    val type: String,

    @ColumnInfo(name = COLUMN_AMOUNT)
    val amount: Double,

    @ColumnInfo(name = COLUMN_DATE)
    val date: Long,

    @ColumnInfo(name = COLUMN_COMMENT)
    val comment: String,

    @ColumnInfo(name = COLUMN_CATEGORY)
    val category: String,

    @ColumnInfo(name = COLUMN_PAYMENT_MODE)
    val paymentMode: String
){

//    override fun toString(): String {
//        return "Expense(id=$id, type='$type', amount=$amount, date=$date, comment='$comment', category='$category', paymentMode='$paymentMode')"
//    }

    companion object {
        const val TABLE_NAME = "expenses"
        const val COLUMN_ID = "id"
        //income or expense
        const val COLUMN_TYPE = "expense_type"
        const val COLUMN_AMOUNT = "expense_amount"
        const val COLUMN_DATE = "expense_date"
        //or can be referred as summary
        const val COLUMN_COMMENT = "expense_comment"
        //food, travel, shopping etc
        const val COLUMN_CATEGORY = "expense_category"
        const val COLUMN_PAYMENT_MODE = "payment_mode"
    }
}